version: '2'

services:
  apache-mod-php:
    image: nikolaslada/stretch-devstack:apache-mod-php

    networks:
      default:
        ipv4_address: 172.10.10.2

    volumes_from:
      - data

    ports:
      - 80:80
      - 443:443

    links:
      - mariadb:mysql

  data:
    image: busybox

    volumes:
       - ./data:/srv

  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MariadDbRoot

    networks:
      default:
        ipv4_address: 172.10.10.3

    ports:
      - 3306:3306

    volumes:
      - ./data/mariadb:/var/lib/mysql

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.10.10.0/24
        gateway: 172.10.10.1
